---
title: "0210ggplot2"
author: "許志瑋"
date: "2017年2月13日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

*必須*要更新教室電腦的 RStudio 版本。

**必須**要更新教室電腦的 RStudio 版本。

***必須***要更新教室電腦的 RStudio 版本。

# 使用 ggplot2

## 散佈圖

## 直方圖

## 長條圖

- 圖形的種類：
    - 散佈圖
    - 直方圖
    - 長條圖

## 寫程式

在段落中寫程式 `plot(stackloss)`

## 散佈圖
```{r}
library(ggplot2)
library(plotly)
scatter_diagram <- 
  ggplot(stackloss ,aes(x = Air.Flow,y = Water.Temp))+
  geom_point()+
  ggtitle("Flow of cooling air vs Cooling Water Inlet Temperature")+
  xlab("Flow of cooling air")+
  ylab("Cooling Water Inlet Temperature")+
  theme(plot.title = element_text(hjust = 0.5,colour = "blue"),axis.title.y=element_text(colour="orange"),axis.title.x=element_text(colour="pink"))
ggplotly(scatter_diagram)
```

## 線圖
```{r}
line_graph <- 
  ggplot(stackloss ,aes(x = Air.Flow,y = Water.Temp))+
  geom_point(colour = "blue")+
  geom_line(colour="orange")+
  ggtitle("Flow of cooling air vs Cooling Water Inlet Temperature")+
  xlab("Flow of cooling air")+
  ylab("Cooling Water Inlet Temperature")+
  theme(plot.title = element_text(hjust = 0.5,colour = "blue"),axis.title.y=element_text(colour="orange"),axis.title.x=element_text(colour="pink"))
ggplotly(line_graph)
```

##線圖2
```{r}
line_graph2 <- 
  ggplot(stackloss ,aes(x = Air.Flow,y = Water.Temp))+
  geom_line(colour="orange")+
  ggtitle("Flow of cooling air vs Cooling Water Inlet Temperature")+
  xlab("Flow of cooling air")+
  ylab("Cooling Water Inlet Temperature")+
  theme(plot.title = element_text(hjust = 0.5,colour = "blue"),axis.title.y=element_text(colour="orange"),axis.title.x=element_text(colour="pink"))
ggplotly(line_graph2)
```

##直方圖
```{r}
histogram <- 
  ggplot(stackloss, aes(x = Air.Flow)) +
  theme(plot.title = element_text(hjust = 0.5,colour = "blue"),axis.title.y=element_text(colour="orange"),axis.title.x=element_text(colour="red"))+
  ggtitle("Flow of cooling air ")+
  xlab("Flow of cooling air")+
  ylab("Frequency")+
  geom_histogram(bins=20)
ggplotly(histogram)
```

##直方圖2
```{r}
histogram2 <-
  ggplot(CO2, aes(x = uptake)) +
  theme(plot.title = element_text(hjust = 0.5,colour = "blue"),axis.title.y=element_text(colour="orange"),axis.title.x=element_text(colour="red"))+
  ggtitle("A numeric vector of carbon dioxide uptake rates ")+
  xlab("umol/m^2 sec")+
  ylab("Frequency")+
  geom_histogram(bins=15) +
  facet_wrap(~ Type) 
ggplotly(histogram2)
```

## 盒鬚圖
```{r}
Box_whiskers <- 
  ggplot(CO2, aes(x = Type, y = conc)) +
  theme(plot.title = element_text(hjust = 0.5,colour = "blue"),axis.title.y=element_text(colour="orange"),axis.title.x=element_text(colour="red"))+
  ggtitle("A numeric vector of ambient carbon dioxide concentrations ")+
  xlab("Type")+
  ylab(" (mL/L)")+
geom_boxplot()
ggplotly(Box_whiskers)
```

##長條圖1
```{r}
Bar_graph <- ggplot(LifeCycleSavings, aes(x = row.names(LifeCycleSavings), y = dpi)) +
  theme(plot.title = element_text(hjust = 0.5,colour = "blue"),axis.title.y=element_text(colour="orange"),axis.title.x=element_text(colour="red"))+
  ggtitle("Real per-capita disposable income ")+
  xlab("US Dollar")+
  ylab(" Country")+
  geom_bar(stat = "identity") + coord_flip()
ggplotly(Bar_graph)
```


##長條圖2
```{r}
Bar_graph2 <- ggplot(mpg, aes(x = class)) +
  theme(plot.title = element_text(hjust = 0.5,colour = "blue"),axis.title.y=element_text(colour="orange"),axis.title.x=element_text(colour="red"))+
  ggtitle("Drive mode ")+
  xlab("Type of car")+
  ylab("Frequency")+
  geom_bar(aes(fill = drv))
ggplotly(Bar_graph2)
```

##長條圖3
```{r}
Bar_graph3 <- ggplot(mpg, aes(x = class)) +
  theme(plot.title = element_text(hjust = 0.5,colour = "blue"),axis.title.y=element_text(colour="orange"),axis.title.x=element_text(colour="red"))+
  ggtitle("Drive mode ")+
  xlab("Type of car")+
  ylab("Frequency")+
  geom_bar(aes(fill = drv),position = "dodge")
ggplotly(Bar_graph3)
```

##長條圖4
```{r}
Bar_graph4 <- ggplot(mpg, aes(x = class)) +
  theme(plot.title = element_text(hjust = 0.5,colour = "blue"),axis.title.y=element_text(colour="orange"),axis.title.x=element_text(colour="red"))+
  ggtitle("Drive mode ")+
  xlab("Type of car")+
  ylab("Percentage")+
  geom_bar(aes(fill = drv),position = "fill")
ggplotly(Bar_graph4)
```
